requests/requests-oauthlib

- requests_oauthlib/oauth1_session.py
just a simple fix on it's vs its
> cleanup docstring of OAuth1Session to fix a typo/usage error

- requests_oauthlib/oauth2_session.py
I'm trying to instantiate an `OAuth2Session` object, and populate information (like `client_id`) *after* the initialization code has already run. This change is necessary for that -- otherwise, I get `AttributeError: 'NoneType' object has no attribute 'client_id'`
> Check if client exists before referencing client_id

- requests_oauthlib/compliance_fixes/__init__.py
- requests_oauthlib/compliance_fixes/slack.py
This PR fix a bug that its get method always returns 'not_authed' on Slack.
To call api methods on Slack, it require a URL including 'token' .
> Add Slack compliance

- docs/oauth2_workflow.rst
I added a basic description of the Legacy Application Flow. It's pretty simple, but it took a bit of tooling around so this should save some people the trouble.
I discovered that client_id is not passed from the OAuth2Session or LegacyApplicationClient when fetch_token is called, which I believe to be a bug.
> Update Legacy Application Flow documentation

- requests_oauthlib/oauth1_session.py
- tests/test_oauth1_session.py
so that callers that catch the exception can introspect the response
> attach the entire response object when raising TokenRequestDenied

- requests_oauthlib/oauth2_session.py
When tokens are refreshed, the **kwargs are not passed through to refresh_tokens. This will lead to parameters like SSL verification, authentication and timeout settings to be dropped.
This patch fixes the problem.
> When refreshing tokens, pass through **kwargs

- requests_oauthlib/oauth2_session.py
As per https://github.com/requests/requests-oauthlib/issues/178#issuecomment-142280502 - the addition of this line caused a regression; the HTTP errors aren't passed on to OAuthlib anymore breaking the exceptions that would normally be raised.
> Don't intercept HTTP errors before OAuthlib can handle them

- docs/examples/real_world_example.rst
This closes #199. I am not sure whether the wording is clear (it sure is not as concise as I would like it to be). Any suggestions on how to rephrase are appreciated.
Cheers
> Added note to Real World Example

- requests_oauthlib/oauth2_session.py
This change adds a Basic Auth header into `fetch_token`.
Why?
The relevant section of the OAuth 2.0 specification, [2.3.1. Client Password](https://tools.ietf.org/html/rfc6749#section-2.3.1) reads:
> Clients in possession of a client password MAY use the
> HTTP Basic authentication scheme...
But for servers, it reads:
> The authorization server MUST support the
> HTTP Basic authentication scheme for authenticating clients
> that were issued a client password.
Clients MAY send Basic Auth,
but servers MUST accept it.
Before this commit, `fetch_token` DOES NOT use this scheme.
Instead, it sends `client_id` and `client_secret` in the body.
The spec says this about that:
> Including the client credentials in the request-body
> using the two parameters is NOT RECOMMENDED
> and SHOULD be limited …
> Added authorization header for token access

- requests_oauthlib/oauth1_auth.py
- requests_oauthlib/oauth2_auth.py
The official documentation says to [subclass `requests.auth.AuthBase`](http://docs.python-requests.org/en/latest/user/authentication/#new-forms-of-authentication), so requests-oauthlib should do that. Requests-oauthlib only supports requests at version 2.0.0 and above, and [the `AuthBase` class existed at version 2.0.0](https://github.com/kennethreitz/requests/blob/2.0/requests/auth.py#L34), so we don't need to worry about ImportErrors.
> Subclass requests.auth.AuthBase

- docs/examples/real_world_example.rst
Code-formatted snippets of code, made the N.B. section adhere to 80-column limit layout.
> "Real world example" formatting fixes

- tests/test_oauth1_session.py
> Skip rsa tests when dependencies not met

- requests_oauthlib/oauth2_session.py
Indeed, we are sending default headers when fetching a token. I thought
it was logic to also send these same default headers (and offer our
users the possibility to set their own headers) in the `refresh_token`
method.
Also, one of the main reason for this is that some applications (the
Flowdock API for instance) do need those headers to return the
appropriate content :)
> [bugfix] Add headers in refresh_token flow

- requests_oauthlib/compliance_fixes/__init__.py
- requests_oauthlib/compliance_fixes/mailchimp.py
- tests/test_compliance_fixes.py
This PR addresses [oauthlib issue #296](https://github.com/idan/oauthlib/issues/296) triggered when MailChimp responds to fetch\_token with scope explicitly set to null.
It also addresses difficulty performing an authenticated request to their metadata endpoint to fetch datacenter information caused by MailChimp setting expires\_in to 0 in the token.
These token entries are [well documented](https://apidocs.mailchimp.com/oauth2/), but surprising and maybe unorthodox.
> MailChimp compliance fixes

- requests_oauthlib/oauth2_session.py
> Preventing sending Basic Auth headers with "None:None"

- .travis.yml
- requests_oauthlib/compliance_fixes/linkedin.py
- requests_oauthlib/compliance_fixes/slack.py
- setup.py
- tests/test_compliance_fixes.py
The tests are clearer and more accurate if we use the [requests-mock](https://github.com/openstack/requests-mock) library for mocking responses from requests. This pull request also adds a test for the Slack compliance fix.
> Use requests-mock library, add tests for Slack compliance fix

- requests_oauthlib/oauth2_session.py
Hello,
I'm using an OAuth2Session object, with the token autorefresh feature, inside a library. This involves some level of concurrent requests. 
I've noticed that some requests were issued without the Authorization header. This was happening around the refresh requests. I've tracked it to the fact that the token was nullified inside the refresh_token method, causing my OAuth2Session instance to lack a token for a short period of time (until a new one is fetched).
The attached changes fixed the issue for me (no token reset, and issue a regular requests.post instead of using the class equivalent). That way the token is simply replaced.
Regards.
> Don't nullify token before refresh

- requests_oauthlib/oauth1_session.py
- tests/test_oauth1_session.py
This was basically suggested in the comments of #149. As i can't commit to this open pull request i make a new one. 
Allow users to pass kwargs to fetch_request_token and fetch_access_token that are then passed to the post method of requests.session. 
I need this for disabling SSL-verification for certain calls. But I don't think it makes sense to implement every possible parameter individually.
> Allow kwargs for fetch_request_token and fetch_access_token to be passed to requests.session

- requests_oauthlib/oauth2_session.py
This should fix issue #227 
Open to review and suggestions if this will conflict with other grant flows.
> Use client_id and client_secret as basic auth credentials if provided

- docs/examples/google.rst
As described in OAuth api documentation[1] endpoints has changed 
Fix #222 
1: https://developers.google.com/identity/protocols/OAuth2WebServer
> Google has changed OAuth 2.0 endpoints

- requests_oauthlib/oauth2_session.py
Hi.
I was using your library to access a webbased API via a proxy server.  The proxy requires authentication.  I found I couldn't refresh the token without adding the proxies parameter to the QAuth2Session class.
I have no idea if this raises other security issues but it works for my useage.  I thought I'd see if was useful in the general sense by creating this pull request.
Thanks,
Chris
> Allows tokens to be refreshed via a proxy

- requests_oauthlib/oauth2_session.py
Some apps do not require the Basic Auth header when fetching a token, and some even outright fail. This happened to me with one of my projects earlier today. With this PR, the basic auth logic branch will only run if `auth` is explicitly `None` e.g. not passing the `auth` kwarg. Specifying `auth=False` will bypass said branch.
I also added support for running `fetch_token()` via a proxy since it is kind of weird that #235 exists for `refresh_token()`, but not for fetching. That and debugging is so much easier with an intercepting proxy which also helped me with the former problem.
> Allow explicit bypass of basic auth logic branch and fetching of tokens via proxy

- requests_oauthlib/oauth2_session.py
- tests/test_oauth2_session.py
Because when doing automatic token refresh, we need a `client_id` and `client_secret` in order to do HTTP Basic auth. This is necessary for automatic [token refresh with Bitbucket](https://developer.atlassian.com/bitbucket/api/2/reference/meta/authentication#refresh-tokens).
> Allow OAuth2 session request() to take client_id and client_secret

- tox.ini
This turns out to have been missing, which makes validating the library before release a bit tricky!
> Add requests-mock to tox dependencies.

- docs/examples/examples.rst
- docs/examples/outlook.rst
#234 In reference to this issue.
Added an example of using requests-oauthlib for Outlook Calender API
> Added Outlook Calender API example

- requests_oauthlib/oauth1_session.py
This change strips new line characters from the response body when requesting access tokens from an oauth server. This solves an error I was encountering when trying to authenticate against the WordPress API which returns a new line after the headers and before the URI-encoded response. 
This is the format specified in [Section 2.3 of RFC 5849](https://tools.ietf.org/html/rfc5849#section-2.3) however validation of the response was failing as \r and \n are not safe characters as defined by oauthlib. This caused an exception to be thrown when calling oauthlib's urldecode function on line 30 of oauth1_session.py. By striping those characters before calling urldecode, the presence of a new line in the response body does not cause an exception to be thrown.
> Strips new lines in fetch_token response body

- requests_oauthlib/oauth2_session.py
Resolves #254.
@singingwolfboy, can you please confirm this doesn't break your use-case?
> Prefer user-supplied auth credentials.

- requests_oauthlib/compliance_fixes/__init__.py
- requests_oauthlib/compliance_fixes/fitbit.py
- tests/test_compliance_fixes.py
This adds a compliance fix for the Fitbit API so that errors that occur during access token or refresh token fetching get properly surfaced.
https://dev.fitbit.com/docs/oauth2/#authorization-errors
We have been using this successfully with the python-fitbit library for a few weeks now: https://github.com/orcasgit/python-fitbit/blob/master/fitbit/compliance.py
> add a fitbit compliance fix

- requests_oauthlib/compliance_fixes/__init__.py
- requests_oauthlib/compliance_fixes/plentymarkets.py
- tests/test_compliance_fixes.py
Plentymarkets uses CamelCase for token responses
See here: https://developers.plentymarkets.com/rest-doc/introduction
The Token Responses are from their docs, they are not mine.
> Make this compatible with plentymarkets

- docs/examples/wso2.rst
- docs/oauth2_workflow.rst
The BackendApplicationClient example in the documentation fails for oauth2 gateways that expect the auth to only be in the header and not in the POST body.  In this example WSO2 as implemented by our org.  
The example was parted together from resolved bugs and appears to work against our gateway.  This request it to help others in the same situation.
> Added example and documentation edit for BackendApplicationClient

- docs/examples/examples.rst
- docs/examples/fitbit.rst
There weren't any Mobile Application Flow examples in the documentation from what I remember, so I wrote a quick one I used in a project recently.
> Added Fitbit OAuth 2 Mobile Application Flow example

- tests/test_core.py
- tests/test_oauth2_session.py
Fixes warnigns when running tests with all warnings on:
$ python -b -Wall -m nose
- DeprecationWarning: Please use assertEqual instead.
- BytesWarning: Comparison between bytes and string
> Fix bytes/str mixups

- .travis.yml
- HISTORY.rst
- requests_oauthlib/__init__.py
- setup.py
- tests/test_compliance_fixes.py
- tests/test_core.py
- tests/test_oauth1_session.py
- tests/test_oauth2_session.py
- tox.ini
I would humbly like to suggest requests-oauthlib drop support for Python
2.6.
The last release of Python 2.6 was 2013-10-29, over 3 years ago. It is
no longer receiving security fixes.
https://www.python.org/dev/peps/pep-0361/
The pip project itself has recently dropped support for 2.6. Their
numbers estimate that Python 2.6 accounts for ~2% of their downloads.
https://github.com/pypa/pip/pull/4343
For projects that still use Python 2.6, they can continue to pip install
an older version.
I've tried my best to remove as much 2.6 specific code as I can,
including the 'Programming Language :: Python :: 2.6' trove classifier
from setup.py. I've also removed Travis CI testing, which should result
in faster testing and fewer wasted resources.
Code removed:
- setup.py cleanups due to fewer …
> Drop support for Python 2.6

- README.rst
Basically, `i.e.` means "in other words", and `e.g.` means "for example".  Since Google and Twitter are not the only possible options in the two cases, "for example" is the correct usage.
> Correct `i.e.` to `e.g.`

- setup.py
Always explicitly close files. Use a context manager to make this easier. Fixes `ResourceWarning` when Python has warnings enabled.
> Clean up ResourceWarning in setup.py

- requests_oauthlib/oauth1_session.py
- tests/test_oauth1_session.py
This pull request adds a `token` property to the `OAuth1Session` class, to match the `token` property on the `OAuth2Session` class. It also changes the `parse_authorization_response` and `_fetch_token` methods to call the setter for this property.
You may notice that these two methods now call `self._populate_attributes()` immediately followed by the `token` setter, which _also_ calls `self._populate_attributes()`. Why the duplication? Because subclasses may override this `token` property to behave differently, while still expecting the base class to populate its internal attributes. This how [Flask-Dance](https://github.com/singingwolfboy/flask-dance) works -- calling the `token` setter activates the token storage backend.
If you examine the `OAuth2Session` class in this project, you …
> OAuth1Session token property

- README.rst
- docs/conf.py
Read the Docs moved hosting to readthedocs.io instead of readthedocs.org. Fix
all links in the project.
For additional details, see:
https://blog.readthedocs.com/securing-subdomains/
> Starting today, Read the Docs will start hosting projects from subdomains on
> the domain readthedocs.io, instead of on readthedocs.org. This change
> addresses some security concerns around site cookies while hosting user
> generated data on the same domain as our dashboard.
Update badge link per the documentation:
https://read-the-docs.readthedocs.io/en/latest/badges.html
> If you leave the version argument off, it will default to your latest
> version. This is probably best to include in your README, since it
> will stay up to date with your Read the Docs project:
> Prefer readthedocs.io instead of readthedocs.org for doc links

- requirements.txt
- setup.py
We're going to release OAuthLib 3.0.0 soon, which contains some breaking changes.
This PR is to avoid problems before we are able to merge #331.
> Pin OAuthlib to avoid breakage with 3.0.0 release

- setup.py
Already included in `install_requires`, which are always included in the requirements. There is no need to list it a second time.
> Drop redundant 'requests' in extras_require

- tests/test_oauth1_session.py
Both Python 2 & Python 3 have the type `bytes`. On Python 2, it is an
alias of str, same as what was previously defined. Makes the code
slightly more forward compatible with Python 3 syntax.
> Remove unnecessary alias 'bytes_type'

- tests/test_oauth1_session.py
- tests/test_oauth2_session.py
Python 2.6 has not been supported since 84ad78ca24e323669a6ceea989390fd7ed9a11bf in the v1.0.0 release.
> Remove testing workarounds for Python 2.6

- tests/test_core.py
- tests/test_oauth1_session.py
- tests/test_oauth2_session.py
More specific asserts generally result in more informative error
messages when tests fail. This practice is recommended by the unittest
docs:
https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertTrue
> This method should also be avoided when more specific methods are
> available (e.g. assertEqual(a, b) instead of assertTrue(a == b)),
> because they provide a better error message in case of failure.
Replace assertTrue(isinstance(...)) with assertIsInstance.
Additionally, replace truthiness checks with precise True/False checks.
This practice is also recommended by the unittest docs:
> assertTrue
>
> Note that this is equivalent to bool(expr) is True and not to expr is
> True (use assertIs(expr, True) for the latter).
Replace assertTrue(...) with assertIs(..., True).
> Use more specific asserts

- setup.py
- tests/test_oauth1_session.py
The RSA tests only pass if `oauthlib[signedtoken]` is installed. `oauthlib[rsa]` is not enough. This brings the dependency in line with the `requirements.txt` file. Skip the test if pyjwt is not installed to avoid a test failure due to an `ImportError`.
> Correct dependency for 'rsa' extra

- HISTORY.rst
- requests_oauthlib/oauth2_session.py
- tests/test_oauth2_session.py
Fixes #278 
I haven't added any tests, but I can later.
> Avoid requests automatic auth

- HISTORY.rst
- requests_oauthlib/oauth2_session.py
- requirements.txt
- setup.py
- tests/test_compliance_fixes.py
- tests/test_oauth2_session.py
Fixes #356, builds on top of #331.
This pull request adds support for OAuthlib 3.0.0, and **drops support** for versions of oauthlib before 3.0.0. I made this pull request based on the code in #331, which I assume is reasonably correct, but I don't have a good way of testing it. I had to make some minor changes to get the tests to pass on Python 3.
I would appreciate some eyes on this. The bulk of the code belongs to @jvanasco.
> Switch to OAuthlib 3.0.0

- requests_oauthlib/compliance_fixes/__init__.py
- requests_oauthlib/compliance_fixes/instagram.py
- tests/test_compliance_fixes.py
Instagram requires access_token to be inserted in the URL of the requests as stated here: https://www.instagram.com/developer/endpoints/.
> add instagram compliance fix

- HISTORY.rst
- requests_oauthlib/oauth2_session.py
- tests/test_oauth2_session.py
> Add force_querystring argument to fetch_token() method

- HISTORY.rst
- docs/oauth2_workflow.rst
- requests_oauthlib/oauth2_session.py
- tests/test_oauth2_session.py
OAuth Mutual TLS is on track to become an IETF standard. It will be used in many high-risk scenarios, including Open Banking (see OpenID FAPI), e-health applications, and e-government applications. This patch adds support for client authentication via MTLS.
> Add Support for OAuth Mutual TLS (draft-ietf-oauth-mtls)

- docs/oauth2_workflow.rst
Fix some typos in refresh section of oauth2 workflow
> docs: Fix typos in token refresh section of oauth2 worflow

- AUTHORS.rst
- requests_oauthlib/compliance_fixes/__init__.py
- requests_oauthlib/compliance_fixes/ebay.py
- requests_oauthlib/oauth2_session.py
- tests/test_compliance_fixes.py
eBay compliance fix as discussed in #403.
Thanks to @thiras and @sambragg for working out what was going on.
This will hopefully make it easier for the next developer who needs to figure this out.
> Add eBay compliance fix

- .readthedocs.yaml
- .travis.yml
- docs/conf.py
- docs/requirements.txt
- requirements-test.txt
- requirements.in
- requirements.txt
- setup.py
- tox.ini
Add docs generation into tox. Took the opportunity to move Black Travis job into Tox as well.
To generate Sphinx (ReadTheDocs) locally, you can run `tox -e docs`
To validate Readme syntax (used when publishing package into Pypi https://pypi.org/project/requests-oauthlib/ ), you can run `tox -e readme`
To validate code syntax, you can run `tox -e black` 
Also fix https://github.com/requests/requests-oauthlib/issues/392 by adding a docutils 0.16 restriction which is blocking ReadTheDocs worker.
> Fix Docs generation - Improve Pipeline

- docs/examples/outlook.rst
- requests_oauthlib/oauth1_session.py
Fix https://requests-oauthlib.readthedocs.io/en/v1.3.0-docs/api.html#requests_oauthlib.OAuth1Session.fetch_request_token
docstring issue resulting in an absent "returns" field.
> Fix Sphinx error for oauth1 fetch_token documentation

- docs/examples/outlook.rst
Given that Python 2 is out of support, the documenation examples should probably use Python 3 syntax (i.e. print as a function, input instead of raw_input) instead of Python 2 syntax.
> Update documentation for Python 3

- .github/workflows/run-tests.yml
- setup.py
- tox.ini
Since Py 3.8 is supported, we should update the "classifiers", as it is shown on PyPI and gives wrong impressions that Py 3.8 is not supported.
This PR also adds Py 3.9 and adds them to CI
> Add Python 3.8 & 3.9 as supported versions

- README.rst
Travis CI has been replaced with GHA, update the README badge.
> Update build badge for GitHub Actions

- .github/workflows/publish-release.yml
- .github/workflows/run-tests.yml
- HISTORY.rst
- docs/conf.py
- docs/contributing.rst
- requests_oauthlib/__init__.py
- tox.ini
After this MR is OK, we can tag the git commit, and it should (hopefully) automatically push the python package to pypi.
Have a look on changelog & new pipeline.
> Release 1.3.1

- requests_oauthlib/oauth1_session.py
Accidentally closed last PR - trying to work out why coverage decreases by -0.0 percent when running coveralls with python version 3.7> 
Related to discussion on #473 #443 #442
Looks like all the uncertainty stems from a slight break for the existing documentation convention/pattern. Method documentation for, fetch_request_token in requests_oauthlib/oauth1_session.py added the double asterisk to the optional argument in the function description. The existing pattern is to add them for the signature and leave them off in the description. Before the doc string was flagged as a raw string, this was generating a warning for Invalid Escape Sequence.
Removing the raw string flag and the asterisks as it breaks the pattern already set.
> Updates docs in oauth_session1 to match existing pattern

- requests_oauthlib/oauth2_session.py
When using the `files` parameter in requests for multipart file uploads, and a token needs to be refreshed, the `files` are passed along with the refresh token request.
This pull request only passes `files` to the actual request (as is the case with `data`).
> Don't pass 'files' through to token refresh

- requests_oauthlib/oauth2_session.py
The WHATWG URL Standard [unambiguously defines the `application/x-www-form-urlencoded` format, its parsing and encoding (which includes UTF-8, but applies additional steps)](https://url.spec.whatwg.org/#application/x-www-form-urlencoded). Consequently, no charset is required, or indeed permitted, with the `application/x-www-form-urlencoded` content type, and supplying one causes issues with some authorization servers.
> Fix for #437 - remove erroneous charset param from Content-Type header

- .github/workflows/run-tests.yml
- AUTHORS.rst
- HISTORY.rst
- setup.py
- tox.ini
Follow on from https://github.com/requests/requests-oauthlib/issues/443 / https://github.com/requests/requests-oauthlib/pull/442.
Python 3.10 was released on 2021-10-04:
* https://discuss.python.org/t/python-3-10-0-is-now-available/10955
> Add support for Python 3.10

- README.rst
- docs/index.rst
The official name of the package in PyPI appears to be [requests-oauthlib](https://pypi.org/project/requests-oauthlib/), with a dash rather than an underscore. Upon further testing it does look like `requests_oauthlib` also works, as this issues a HTTP 301 (Moved Permanently) to the version with the dash, so this change isn't strictly necessary, but it seems like a good idea for the documentation to point at the canonical name of the package in PyPI. Feel free to close without merging if you disagree. My feelings won't be hurt.
> Fix typo in PyPI package name in installation instructions

- README.rst
The old destination is no longer working.
http://python-requests.org --> https://requests.readthedocs.io
> README.rst: Update the URL for requests

- tox.ini
```
$ tox -av
...
default environments:
py27   -> run test on python2.7
py34   -> run test on python3.4
py35   -> run test on python3.5
py36   -> run test on python3.6
py37   -> run test on python3.7
py38   -> run test on python3.8
py39   -> run test on python3.9
py310  -> run test on python3.10
pypy   -> run test on pypy
pypy3  -> run test on pypy3
docs   -> mimic readthedocs build
readme -> mimic pypi validation of readme/rst files
black  -> show diff of code format
```
> Give description to tox environments

- .github/workflows/publish-release.yml
- .github/workflows/run-tests.yml
- setup.py
- tox.ini
Python 3.11 was [released on 2022-10-24](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk) 🚀 
[![image](https://user-images.githubusercontent.com/1324225/198233993-5b79523b-370f-4316-a4be-9403c8209068.png)](https://discuss.python.org/t/python-3-11-0-final-is-now-available/20291?u=hugovk)
The [Python 3.12 release candidate is out!](https://discuss.python.org/t/python-3-12-0-release-candidate-1-released/31137?u=hugovk) :rocket:
> ## Call to action
> 
> We strongly encourage maintainers of third-party Python projects to prepare their projects for 3.12 compatibilities during this phase, and where necessary publish Python 3.12 wheels on PyPI to be ready for the final release of 3.12.0.
See also https://dev.to/hugovk/help-test-python-312-beta-1508/
> Add support for Python 3.11 and 3.12

- .github/workflows/run-tests.yml
- AUTHORS.rst
- HISTORY.rst
- docs/conf.py
- docs/contributing.rst
- docs/requirements.txt
- requests_oauthlib/__init__.py
- requests_oauthlib/compliance_fixes/__init__.py
- requests_oauthlib/oauth2_session.py
- requirements-test-27.txt
- requirements-test.txt
- requirements.txt
- tests/test_oauth1_session.py
- tox.ini
This should be the first step to 1.4.0 release, and a refresh of python versions. The codebase hasn't been cleaned, but it can come at a later point in time, or gradually depending the files changes.
The more important is to keep the latest tools (tox, cicd) up to date to allow MR to be included and release more often.
> Removed older python versions (2.7,<=3.7)

- docs/examples/bitbucket.rst
- docs/examples/facebook.rst
- docs/examples/github.rst
- docs/examples/tumblr.rst
- docs/oauth1_workflow.rst
- docs/oauth2_workflow.rst
- requests_oauthlib/oauth1_session.py
I recently came across this library and saw that it still had Python 2 references in the docs. I saw #523 was open, so I went ahead and updated the documentation to use Python 3 examples.
Once #523 is merged this could be merged as well.
---
*(Out of scope, but leaving this here for now, could make this a separate issue)*
Now that we're dropping Python <=3.7 there are a lot of Python 3 related changes and quality of life improvements we can now make:
* Add type annotations
* Remove remaining Python 2 compatibility checks
* Improve testing infrastructure
I wouldn't mind working on these in my free time if we decide these would be useful!
> Update Python 2 examples in docs to Python 3

- docs/oauth2_workflow.rst
Throughout the Worker example code, the `client` variable is assigned an `ApplicationClient` derived class object (e.g. BackendApplicationClient), and the `oauth` variable is assigned an `OAuth2Session` object.  However, in the 'Refreshing tokens' section the `client` is assigned an `OAuth2Session` object.  This change updates the latter section to use the variable convention of the former sections.
> Put OAuth2Session in 'oauth' consistently in examples

- .gitignore
- HISTORY.rst
- docs/examples/native_spa_pkce_auth0.py
- requests_oauthlib/__init__.py
- requirements-test.txt
- tests/examples/base.py
- tests/examples/test_native_spa_pkce_auth0.py
- tox.ini
Initial attempt to add automation & test on  examples found in the docs.
Added PKCE only for now.
Any feedbacks are welcome.
> Add Tests for Examples in docs

- HISTORY.rst
- requests_oauthlib/__init__.py
Hi, 
A new 1.4.0 is being prepared, feel free to test before we do the actual release either with this branch, or with pip with the "prerelease" version published in pypi: https://pypi.org/project/requests-oauthlib/1.4.0.dev0/
> 1.4.0 release candidate

- HISTORY.rst
- requests_oauthlib/__init__.py
> Preparing the 2.0.0 to replace 1.4.0
